name: "Terraform CI"

on:
  push:
    branches:
      - master

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./gcp

    env:
      TF_VAR_project_id: ${{ secrets.TF_VAR_PROJECT_ID }}
      TF_VAR_region: ${{ secrets.TF_VAR_REGION }}
      TF_VAR_admin_member: ${{ secrets.TF_VAR_ADMIN_MEMBER }}
      TF_VAR_helm_sa_name: helm-sa
      TF_VAR_db_user_password: ${{ secrets.TF_VAR_DB_USER_PASSWORD }}
      TF_VAR_k8s_neg_name: cycling-buddies-api-service-neg

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.13.5

      - name: Terraform Init
        run: terraform init
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.TF_GOOGLE_CREDENTIALS }}

      - name: Terraform Format
        run: terraform fmt

      - name: Terraform Refresh
        run: terraform refresh
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.TF_GOOGLE_CREDENTIALS }}

      - name: Terraform Plan
        run: terraform plan
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.TF_GOOGLE_CREDENTIALS }}

      - name: Terraform Apply
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: terraform apply -auto-approve
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.TF_GOOGLE_CREDENTIALS }}
